In [1]:
import numpy as np

In [3]:
A = np.array([[56, 0, 4.4, 68],
             [1.2,  104, 52, 8],
             [1.8, 135, 99, 0.9]])

In [4]:
A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [5]:
cal = A.sum(axis=0)

In [12]:
cal

array([ 59. , 239. , 155.4,  76.9])

In [10]:
100*A/cal.reshape(1,4) # percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [12]:
import numpy as np
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [13]:
c.shape

(3, 3)

In [14]:
a

array([[ 0.50816599,  0.73067996, -0.76943423],
       [ 0.71246442,  0.83768729,  1.25552168],
       [ 0.32509206,  0.14592124,  0.28213568]])

In [15]:
b

array([[-0.23900217],
       [ 0.29489882],
       [ 2.22896252]])

In [16]:
c

array([[-0.12145277, -0.17463409,  0.18389645],
       [ 0.21010491,  0.24703299,  0.37025186],
       [ 0.72461801,  0.32525297,  0.62886986]])

In [28]:
a = np.random.randn(4, 3) # a.shape = (2, 3)
b = np.random.randn(4, 1) # b.shape = (2, 1)
c = a + b

In [29]:
c.shape

(4, 3)

In [30]:
a

array([[ 0.93717516,  1.02799764,  0.65717002],
       [ 0.58414407, -0.44003502,  1.42961625],
       [-0.04763588, -0.86788817, -0.70567445],
       [ 0.66709479, -0.26459488, -0.30190991]])

In [31]:
b

array([[-0.07858865],
       [-0.1508364 ],
       [ 0.32140133],
       [ 0.17739968]])

In [32]:
c

array([[ 0.8585865 ,  0.94940899,  0.57858136],
       [ 0.43330768, -0.59087141,  1.27877985],
       [ 0.27376545, -0.54648683, -0.38427311],
       [ 0.84449448, -0.0871952 , -0.12451023]])

In [19]:
# a.shape = (3,4)
# b.shape = (4,1)

for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]

IndexError: index 3 is out of bounds for axis 0 with size 3